modLoader="javafml" #mandatory
loaderVersion="[41,)" #mandatory
license="https://en.wikipedia.org/wiki/MIT_License"
[[mods]] #mandatory
modId="cosmere" #mandatory
version="${file.jarVersion}" #mandatory
displayName="The Cosmere" #mandatory
logoFile="cosmere_icon.png"
credits="Special thanks to 50ap5ud5, Suff, Spectre0987, Vazkii, the Chisels and Bits team and so many more. \nThey all either helped me (directly or indirectly via their open source repos) understand working with the minecraft and the forge API better <3\nSeriously. Thank you!" #optional
authors="Leaf Reynolds" #optional
description='''
Bringing The Cosmere to Minecraft!
'''

[[dependencies.cosmere]]
modId="forge"
mandatory=true
versionRange="[41.0.64,)"
ordering="NONE"
side="BOTH"

[[dependencies.cosmere]]
modId="minecraft"
mandatory=true
versionRange="[1.19,1.20)"
ordering="NONE"
side="BOTH"

[[dependencies.cosmere]]
modId="curios"
mandatory=true
versionRange="[1.19-5.1.0.3,)"
ordering="NONE"
side="BOTH"
