modLoader = "javafml"
loaderVersion = "${loader_version}"
issueTrackerURL = "https://github.com/leafreynolds/Cosmere/issues"
license = "MIT"

[[mods]]
modId = "feruchemy"
version = "${version}"
displayName = "Cosmere: Feruchemy"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/cosmere"
authors = "Leafy"
credits = "Ridanisaurus, Arkamis13, Luke13234, Hawktrav and many others"
logoFile = "logo.png"
description = '''Feruchemy module for Cosmere.'''

[[dependencies.feruchemy]]
modId = "cosmere"
mandatory = true
versionRange = "[${version}]"
ordering = "AFTER"
side = "BOTH"

[[dependencies.feruchemy]]
modId = "allomancy"
mandatory = false
versionRange = "[${version}]"
ordering = "AFTER"
side = "BOTH"

[[dependencies.feruchemy]]
modId = "hemalurgy"
mandatory = false
versionRange = "[${version}]"
ordering = "BEFORE"
side = "BOTH"